let careData = [   
    {
        id: 31,
        category: "Ošetřující prostředky",
        link: "store.html#caring",
        categoryColor: "#246A73",
        productName: "DONIWAX vosk 5 l",
        unit: "l",
        amount: 5,
        shortDescription: "Podlahový vosk a lesk na všechny vodovzdorné povrchy",
        img: "/img/doniwax 5.png",
        longDescription: "<p>Tekutý metal-akrylový vosk používaný na všechny vodovzdorné povrchy, kámen, vinyl, marmoleum, korek, linoleum, keramika, guma, dřevo apod.</p><p>Doniwax vosk je rychle schnoucí, protiskluzný, vhodný pro vysoce rychlostní leštění. Po aplikaci zanechává lesklý ochranný povlak.</p>",
        preicePerKg: "26600",
        pricePerKgVat: "32186",
        pricePerUnit: "133000",
        pricePerUnitVat: "160930",
        howToUse: "<p>Silně znečištěné plochy umyjte přípravkem FLOORWASH (na povrchy jako je dlažba, kámen apod.) v poměru 1:3 – 1:5 (na odstranění starých vosků a silnějších nánosů) s vodou (30 - 40°C).</p><p>Při menším znečištění použijte v poměru 1:80 až 1:100. Podlaha musí být naprosto čistá a pH podlahy musí být 7 (měříme pH papírky). Pokud pH není 7 (neutrální) lze pH snížit tak, že povrch setřete čistou vodou s přídavkem octa (ocet snižuje hodnotu pH).</p><p>Před nanášením vosku musí být povrch suchý. Na takto odmaštěnou a čistou plochu naneste Doniwax a nechte zaschnout cca 1 hodinu. Po zaschnutí první vrstvy, můžete stejným způsobem nanést další až 3 vrstvy.</p>",
        dataSheet: "/downloads/doniwax data.pdf",
        properties: "<p>Bezbarvá kapalina.</p>",
        safetySheet: "/downloads/doniwax safety.pdf"
    },
    {
        id: 32,
        category: "Ošetřující prostředky",
        categoryColor: "#246A73",
        link: "store.html#caring",
        productName: "ENNATE 1 kg",
        unit: "kg",
        amount: 1,
        shortDescription: "Ochranný přípravek na nerezové povrchy, plasty, HPL",
        img: "/img/ennate 1.png",
        longDescription: "<p>Přípravek je vhodné použít k ochraně všech druhů povrchů. Přípravek ochraňuje povrchy, tím, že na povrchu vytvoří ochranný film. Zabraňuje opotřebovávání povrchů a zaručuje další snadnější čištění. Po aplikaci povrch odolává proti dalšímu lehčímu znečištění jako jsou otisky prstů a vody. Používá se na digestoře, nerezové stoly, HPL skříně a zařízení, myčky, vozíky, výtahy, zábradlí, trouby, lednice, apod.</p>",
        preicePerKg: "32600",
        pricePerKgVat: "39446",
        pricePerUnit: "32600",
        pricePerUnitVat: "39446",
        howToUse: "<p>Přípravek se neředí vodou. Používá se jako koncentrát. Neaplikujte na povrchy, které mají přímý styk s potravinami. Aplikujte na suchý a čistý povrch a důkladně rozleštěte.</p>",
        dataSheet: "/downloads/ennate data.pdf",
        properties: "<p>Bílá až nažloutlá kapalina, zápach: slabý, specifický, pH: 6,0-10,0 (roztok při 20 °C).</p>",
        safetySheet: ""
    },
    {
        id: 33,
        category: "Ošetřující prostředky",
        categoryColor: "#246A73",
        link: "store.html#caring",
        productName: "ENNATE 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Ochranný přípravek na nerezové povrchy, plasty, HPL",
        img: "/img/ennate 5.png",
        longDescription: "<p>Přípravek je vhodné použít k ochraně všech druhů povrchů. Přípravek ochraňuje povrchy, tím, že na povrchu vytvoří ochranný film. Zabraňuje opotřebovávání povrchů a zaručuje další snadnější čištění. Po aplikaci povrch odolává proti dalšímu lehčímu znečištění jako jsou otisky prstů a vody. Používá se na digestoře, nerezové stoly, HPL skříně a zařízení, myčky, vozíky, výtahy, zábradlí, trouby, lednice, apod.</p>",
        preicePerKg: "29700",
        pricePerKgVat: "35937",
        pricePerUnit: "148500",
        pricePerUnitVat: "179685",
        howToUse: "<p>Přípravek se neředí vodou. Používá se jako koncentrát. Neaplikujte na povrchy, které mají přímý styk s potravinami. Aplikujte na suchý a čistý povrch a důkladně rozleštěte.</p>",
        dataSheet: "/downloads/ennate data.pdf",
        properties: "<p>Bílá až nažloutlá kapalina, zápach: slabý, specifický, pH: 6,0-10,0 (roztok při 20 °C).</p>",
        safetySheet: ""
    },
];

/* Template
    {
        id: ,
        category: "Ošetřující prostředky",
        categoryColor: "#246A73",
        link: "store.html#caring",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "<p></p>",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "<p></p>",
        dataSheet: "",
        properties: "<p></p>",
        safetySheet: ""
    },
*/