let cleanData = [   
    {
        id: 11,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 6.png",
        longDescription: "<p>Silně alkalický, nepěnivý čistící a odmašťující přípravek.</p><p>Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.</p>",
        preicePerKg: "19900",
        pricePerKgVat: "24070",
        pricePerUnit: "119400",
        pricePerUnitVat: "144474",
        howToUse: "<p>Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody).</p><p>Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).</p>",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "<p>Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.</p>",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 12,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASHCLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Silně alkalický, nepěnivý čistící a odmašťující přípravek",
        img: "/img/washclean 30.png",
        longDescription: "<p>Silně alkalický, nepěnivý čistící a odmašťující přípravek.</p><p>Používá se na vodovzdorné povrchy, podlahy a technologická zařízení v potravinářství, stravovacích provozech, bazénech, kotelnách k vnitřnímu čištění potrubí a nádrží, apod.</p>",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "537000",
        pricePerUnitVat: "649770",
        howToUse: "<p>Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody).</p><p>Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).</p>",
        dataSheet: "/downloads/washclean data.pdf",
        properties: "<p>Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.</p>",
        safetySheet: "/downloads/washclean safety.pdf"
    },
    {
        id: 13,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 6.png",
        longDescription: "<p>Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod.</p><p>Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.</p>",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "125400",
        pricePerUnitVat: "151734",
        howToUse: "<p>Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění.</p><p>Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou.</p><p>Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem.</p><p>Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).</p>",
        dataSheet: "/downloads/floorwash data.pdf",
        properties: "<p>Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.</p>",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 14,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "FLOORWASH 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Alkalický, nepěnivý, čistící a odmašťující přípravek",
        img: "/img/floorwash 30.png",
        longDescription: "<p>Alkalický, nepěnivý, čistící a odmašťující přípravek. Používá se na vodovzdorné povrchy, podlahy a technologická zařízení. Vhodný i pro odstranění podlahových vosků v tělocvičnách, školách, k odstranění šmouh od obuvi, komunálních budovách apod.</p><p>Také odstraňuje pryskyřici z dřevěných podlah, hoblovek a pilových listů.</p>",
        preicePerKg: "18600",
        pricePerKgVat: "22506",
        pricePerUnit: "558000",
        pricePerUnitVat: "675180",
        howToUse: "<p>Generální úklid a odmaštění: smíchejte s vodou v poměru 1:1 – 1:20 (5 dl na 10 l vody) v závislosti na znečištění.</p><p>Odstranění podlahových vosků: smíchejte s vodou v poměru 1:40 (2,5 dl na 10 l vody) s teplou vodou.</p><p>Odstranění pryskyřice: aplikujte rozprašovačem, houbou apod. Nechte působit a poté setřete vlhkým hadříkem.</p><p>Běžný úklid: smíchejte s vodou v poměru 1:100 (1dl na 10 l vody).</p>",
        dataSheet: "downloads/floorwash data.pdf",
        properties: "<p>Bezbarvá kapalina. Hodnota pH (20 °C): 13,5. Bez zápachu.</p>",
        safetySheet: "/downloads/floorwash safety.pdf"
    },
    {
        id: 15,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "GASTRO CLEAN 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Čistící a odmašťující přípravek pro všechny typy myček nádobí",
        img: "/img/gastro clean 30.png",
        longDescription: "<p>Silně alkalický, nepěnivý čistící a odmašťující přípravek pro všechny typy myček nádobí s možností ručního i automatického dávkování.</p><p>Silný koncentrát bez nepříjemného zápachu. Odstraňuje zbytky jídel všeho druhu.</p><p>Nepoužívat na hliníkové nádobí z důvodu vzniku možné koroze.</p>",
        preicePerKg: "13900",
        pricePerKgVat: "16819",
        pricePerUnit: "417000",
        pricePerUnitVat: "504570",
        howToUse: "<p>Dávkujte 1-3 ml na 1 l vody.</p><p>Záleží na tvrdosti vody. V případě velké tvrdosti vody zvyšte dávkování dle potřeby.</p>",
        dataSheet: "/downloads/gastro clean data.pdf",
        properties: "<p>Světležlutá kapalina, pH 11,0-13,5 (3% roztok při 20 °C). Zápach: slabý, charakteristický.</p>",
        safetySheet: "/downloads/gastro clean safety.pdf"
    },
    {
        id: 16,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "SOFT FLOOR 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Čisticí přípravek na koberce a interiéry aut, linoleum, dlažbu",
        img: "/img/soft floor 5.png",
        longDescription: "<p>Používá se na odstranění nečistot. Vhodné zejména pro čištění linolea, dlažba, koberce.</p><p>Velice se osvědčil při čištění interiérů automobilů.</p><p>Účinně odstraňuje mastnotu a zanechává dlouhotrvající vůni.</p><p>Neobsahuje fosfáty.</p>",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "89500",
        pricePerUnitVat: "108295",
        howToUse: "<p>Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod.</p><p>Teplota vody 0° - 80°C. Nejlépe funguje při použití teplé vody.</p><p>Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou.</p><p>S opatrností může být používán na hliník a jiné alkalitám neodolné materiály.</p><p>Dávkování: 1l: 50 l vody.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/soft floor safety.pdf"
    },
    {
        id: 17,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "SPRING 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Mycí přípravek pro ruční mytí nádobí s vůní limetky",
        img: "/img/spring 5.png",
        longDescription: "<p>Mycí přípravek pro ruční mytí nádobí s vůní limetky. Účinně rozpouští mastnotu, oleje a nečistoty.</p>",
        preicePerKg: "6500",
        pricePerKgVat: "7865",
        pricePerUnit: "32500",
        pricePerUnitVat: "39325",
        howToUse: "<p>Běžné mytí nádobí: 1 ml na 5 l vody do dřezu.</p><p>Na čištění povrchů: 5 ml na 5 l vody.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/spring safety.pdf"
    },
    {
        id: 18,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RUDON 6 kg",
        unit: "kg",
        amount: 6,
        shortDescription: "Pěnivý čistící přípravek na odstranění tuků, napečenin atd.",
        img: "/img/rudon 6.png",
        longDescription: "<p>Silně alkalický pěnivý čistící přípravek. Používá se na odstranění tuků, napečenin atd.</p><p>Vhodné zejména pro čištění v potravinářském průmyslu. Používá se na trouby, pece, konvektomaty, grily, atd.</p><p>Pěnivý přípravek, který lze snadno opláchnout. Účinně odstraňuje mastnotu a nezanechává nepříjemný zápach.</p><p>Neobsahuje fosfáty.</p>",
        preicePerKg: "19400",
        pricePerKgVat: "23474",
        pricePerUnit: "116400",
        pricePerUnitVat: "140844",
        howToUse: "<p>Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod.</p><p>Teplota vody 0° - 80°C. Nejlépe funguje při použití teplé vody.</p><p>Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou. Po aplikaci musí být plochy, které přicházejí do styku s poživatinou opláchnuty dostatečným množstvím čisté vody.</p><p>S opatrností může být používán na hliník a jiné alkalitám neodolné materiály.</p>",
        dataSheet: "/downloads/rudon data.pdf",
        properties: "<p>Nažloutlá kapalina, pH: 12-14 (1% roztok při 20 °C) Zápach: slabý.</p>",
        safetySheet: "/downloads/rudon safety.pdf"
    },
    {
        id: 19,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RUDON 30 kg",
        unit: "kg",
        amount: 30,
        shortDescription: "Pěnivý čistící přípravek na odstranění tuků, napečenin atd.",
        img: "/img/rudon 30.png",
        longDescription: "<p>Silně alkalický pěnivý čistící přípravek. Používá se na odstranění tuků, napečenin atd.</p><p>Vhodné zejména pro čištění v potravinářském průmyslu. Používá se na trouby, pece, konvektomaty, grily, atd.</p><p>Pěnivý přípravek, který lze snadno opláchnout. Účinně odstraňuje mastnotu a nezanechává nepříjemný zápach.</p><p>Neobsahuje fosfáty.</p>",
        preicePerKg: "18100",
        pricePerKgVat: "21901",
        pricePerUnit: "543000",
        pricePerUnitVat: "657030",
        howToUse: "<p>Aplikuje se pomocí nízkotlakového pěnovacího zařízení, rozprašovače apod.</p><p>Teplota vody 0° - 80°C. Nejlépe funguje při použití teplé vody.</p><p>Po aplikaci se přípravek nechá působit cca 5 minut. Před zaschnutím opláchnout čistou vodou. Po aplikaci musí být plochy, které přicházejí do styku s poživatinou opláchnuty dostatečným množstvím čisté vody.</p><p>S opatrností může být používán na hliník a jiné alkalitám neodolné materiály.</p>",
        dataSheet: "/downloads/rudon data.pdf",
        properties: "<p>Nažloutlá kapalina, pH: 12-14 (1% roztok při 20 °C) Zápach: slabý.</p>",
        safetySheet: "/downloads/rudon safety.pdf"
    },
    {
        id: 110,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "UNIPROF 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Čistící přípravek na okna, voděodolné povrchy, sanitární zařízení",
        img: "/img/uniprof 5.png",
        longDescription: "<p>Efektivní koncentrovaný čisticí přípravek určený pro mytí oken bez leštění, každodenní údržbu voděodolných povrchových materiálů, plastových rámů oken, skříněk, stolů a parapetů.</p><p>Vhodný pro pravidelné čištění většiny povrchových materiálů, jako je podlahová dlažba, parkety, plovoucí podlaha, linoleum, marmoleum, kámen atd.</p>",
        preicePerKg: "18700",
        pricePerKgVat: "22627",
        pricePerUnit: "93500",
        pricePerUnitVat: "113135",
        howToUse: "<p>Přípravek je určen pro ruční mytí. Je-li přípravek používán dle doporučení nezanechává po aplikaci na povrchu mapy po mytí.</p><p>Dávkujte do teplé vody.</p><p>Ruční mytí: okna, skla 3 ml na 10 litrů vody.</p><p>Běžné znečištění: 0,5 dc na 10 litrů vody.</p><p>Větší znečištění 1 dc na 10 litrů vody.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/uniprof grep safety.pdf"
    },
    {
        id: 111,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "Rambo písek 650 ml (14 ks)",
        unit: "ks",
        amount: 14,
        shortDescription: "Tekutý písek na mytí nádobí a čištění povrchů",
        img: "/img/rambo sand 0,650.png",
        longDescription: "<p>Vysoce účinný tekutý písek pro mytí nádobí a čištění silně znečištěných povrchů různých materiálů.</p><p>Obsah balení: 14 ks.</p>",
        preicePerKg: "4200",
        pricePerKgVat: "5082",
        pricePerUnit: "58800",
        pricePerUnitVat: "71148",
        howToUse: "<p>Použití na nádobí: naneste malé množství tekutého písku na houbičku nebo hadřík, jemně vydrhněte povrch a opláchněte čistou vodou.</p><p>Použití na silně znečištěné povrchy: aplikujte přímo na znečištěné místo, nechte krátce působit, poté mechanicky očistěte a opláchněte.</p><p>Nepoužívejte na citlivé povrchy náchylné k poškrábání.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/rambo sand safety.pdf"
    },
    {
        id: 112,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RAMBO WC 750 ml (10 ks)",
        unit: "ks",
        amount: 10,
        shortDescription: "Kyselý čistič sanitárních zařízení a keramiky",
        img: "/img/rambo wc 0,750.png",
        longDescription: "<p>Kyselý čistič (kachna) je určen k mytí a ošetřování sanitárních zařízení a keramiky.</p><p>Je vhodný k odstraňování rzi a vodního kamene. Používá se na všechny kyselinovzdorné materiály, jako je porcelán, keramika apod.</p><p>Efektivně odstraňuje i silné vrstvy vodního kamene.</p><p>Obsah balení: 10 ks.</p>",
        preicePerKg: "5800",
        pricePerKgVat: "7018",
        pricePerUnit: "58000",
        pricePerUnitVat: "70180",
        howToUse: "<p>Používá se na jednorázový úklid. Přípravek se neředí.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: "/downloads/rambo wc safety.pdf"
    },
    {
        id: 113,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "RAMBO mléko 650 ml<br>(14 ks)",
        unit: "ks",
        amount: 14,
        shortDescription: "Čistící mléko na ruce",
        img: "/img/rambo milk 0,650.png",
        longDescription: "<p>Vysoce účinný prostředek k mytí silně znečištěných rukou zejména od šmíru, oleje, ale i dalšího znečištění.</p>",
        preicePerKg: "4400",
        pricePerKgVat: "5324",
        pricePerUnit: "61600",
        pricePerUnitVat: "74536",
        howToUse: "<p>Na zašpiněné ruce použijte potřebné množství přípravku a bez použití vody po dobu cca půl minuty ruce myjte, poté ruce opláchněte proudem tekoucí vody.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
    {
        id: 114,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "Donilex 5 l",
        unit: "l",
        amount: 5,
        shortDescription: "Mycí a konzervační přípravek s protiskluzným voskem",
        img: "/img/donilex 5.png",
        longDescription: "<p>Denní mycí a konzervační přípravek s protiskluzným voskem na všechny voděodolné povrchy: podlahová dlažba, parkety, plovoucí podlaha, linoleum, marmoleum, kámen apod.</p><p>Zanechává na povrchu ochrannou vrstvu, která brání vzniku povrchových změn, zajišťuje čistý a lesklý vzhled a usnadňuje následné čištění.</p>",
        preicePerKg: "25700",
        pricePerKgVat: "31097",
        pricePerUnit: "128500",
        pricePerUnitVat: "155485",
        howToUse: "<p>Ruční a strojové mytí: 1:100 (1dl na 10 l vody).</p>",
        dataSheet: "",
        properties: "<p>Bílá kapalina, zápach charakteristický, pH: 8,50.</p>",
        safetySheet: "/downloads/donilex safety.pdf"
    },
    {
        id: 115,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASH RINSE 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Oplachový prostředek pro profesionální myčky nádobí",
        img: "/img/wash rinse 5.png",
        longDescription: "<p>Oplachový prostředek pro profesionální myčky nádobí, které mají automatický dávkovací systém zabudovaný v myčce nebo dávkování přes dávkovací čerpadlo.</p><p>Zaručuje vysoký lesk, rychlé schnutí bez tvorby kapek na nádobí, sklenicích, příborech apod.</p>",
        preicePerKg: "20500",
        pricePerKgVat: "24805",
        pricePerUnit: "102500",
        pricePerUnitVat: "124025",
        howToUse: "<p>Dávkujte 2 – 10 ml na 10 l vody.</p>",
        dataSheet: "/downloads/wash rinse data.pdf",
        properties: "<p>Čirá světlemodrá kapalina, pH 2,1 - 4,0 (3% roztok při 20 °C). Zápach: slabý, charakteristický.</p>",
        safetySheet: "/downloads/wash rinse safety.pdf"
    },
    {
        id: 115,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "WASH RINSE 20 kg",
        unit: "kg",
        amount: 20,
        shortDescription: "Oplachový prostředek pro profesionální myčky nádobí",
        img: "/img/wash rinse 20.png",
        longDescription: "<p>Oplachový prostředek pro profesionální myčky nádobí, které mají automatický dávkovací systém zabudovaný v myčce nebo dávkování přes dávkovací čerpadlo.</p><p>Zaručuje vysoký lesk, rychlé schnutí bez tvorby kapek na nádobí, sklenicích, příborech apod.</p>",
        preicePerKg: "18900",
        pricePerKgVat: "22869",
        pricePerUnit: "378000",
        pricePerUnitVat: "457380",
        howToUse: "<p>Dávkujte 2 – 10 ml na 10 l vody.</p>",
        dataSheet: "/downloads/wash rinse data.pdf",
        properties: "<p>Čirá světlemodrá kapalina, pH 2,1 - 4,0 (3% roztok při 20 °C). Zápach: slabý, charakteristický.</p>",
        safetySheet: "/downloads/wash rinse safety.pdf"
    },
];

/* Template
    {
        id: ,
        category: "Čisticí prostředky",
        categoryColor: "rgb(51, 70, 116)",
        link: "store.html#cleaning",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "<p></p>",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "<p></p>",
        dataSheet: "",
        properties: "<p></p>",
        safetySheet: ""
    },
*/