let desinfectionData = [   
    {
        id: 21,
        category: "Dezinfekční prostředky",
        categoryColor: "#4474ac",
        link: "store.html#desinfection",
        productName: "REGIA 5 l",
        unit: "l",
        amount: 5,
        shortDescription: "Antibakteriální tekuté mýdlo na ruce",
        img: "/img/regia 5.png",
        longDescription: "<p>Antibakteriální tekuté mýdlo na ruce je účinný prostředek pro každodenní hygienu.</p><p>Díky speciálním složkám pomáhá odstraňovat nečistoty, bakterie a nepříjemné pachy, zatímco zanechává pokožku jemnou a svěží.</p><p>Vhodné pro domácnosti, veřejné prostory i profesionální využití.</p>",
        preicePerKg: "9900",
        pricePerKgVat: "11979",
        pricePerUnit: "49500",
        pricePerUnitVat: "59895",
        howToUse: "<p>Naneste malé množství mýdla na vlhké ruce, důkladně rozetřete po celé ploše a opláchněte čistou vodou.</p>",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
    {
        id: 22,
        category: "Dezinfekční prostředky",
        categoryColor: "#4474ac",
        link: "store.html#desinfection",
        productName: "Dez Gel 1 kg",
        unit: "kg",
        amount: 1,
        shortDescription: "Dezinfekční gel k hygienické dezinfekci rukou",
        img: "/img/dez gel 1.png",
        longDescription: "<p>Dezinfekční gel na hygienickou dezinfekci rukou je praktickým řešením pro každodenní ochranu. Účinně eliminuje bakterie a viry a zajišťuje čisté a bezpečné ruce kdykoli a kdekoli. Perfektní volba pro udržení hygieny doma, v práci i na cestách.</p>",
        preicePerKg: "21900",
        pricePerKgVat: "26499",
        pricePerUnit: "21900",
        pricePerUnitVat: "26499",
        howToUse: "<p>3 ml přípravku vtírat do suchých rukou po dobu 30 sekund a jednou opakovat.</p>",
        dataSheet: "",
        properties: "<p>Čirá kapalina, barva: modrá, zápach: alkoholický, pH 5,5–7,0.</p>",
        safetySheet: "/downloads/dez gel safety.pdf"
    },
    {
        id: 23,
        category: "Dezinfekční prostředky",
        categoryColor: "#4474ac",
        link: "store.html#desinfection",
        productName: "Dez Gel 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Dezinfekční gel k hygienické dezinfekci rukou",
        img: "/img/dez gel 5.png",
        longDescription: "<p>Dezinfekční gel na hygienickou dezinfekci rukou je praktickým řešením pro každodenní ochranu. Účinně eliminuje bakterie a viry a zajišťuje čisté a bezpečné ruce kdykoli a kdekoli. Perfektní volba pro udržení hygieny doma, v práci i na cestách.</p>",
        preicePerKg: "17900",
        pricePerKgVat: "21659",
        pricePerUnit: "89500",
        pricePerUnitVat: "108295",
        howToUse: "<p>3 ml přípravku vtírat do suchých rukou po dobu 30 sekund a jednou opakovat.</p>",
        dataSheet: "",
        properties: "<p>Čirá kapalina, barva: modrá, zápach: alkoholický, pH 5,5–7,0.</p>",
        safetySheet: "/downloads/dez gel safety.pdf"
    },
    {
        id: 24,
        category: "Dezinfekční prostředky",
        categoryColor: "#4474ac",
        link: "store.html#desinfection",
        productName: "Amphospray 1 l",
        unit: "l",
        amount: 1,
        shortDescription: "Bezoplachová dezinfekce",
        img: "/img/amphospray 1.png",
        longDescription: "<p>Dezinfekce více druhů povrchů pomocí alkoholového roztoku.</p>",
        preicePerKg: "33200",
        pricePerKgVat: "40172",
        pricePerUnit: "33200",
        pricePerUnitVat: "40172",
        howToUse: "<p>Naneste roztok přímo na povrch. Nechte volně zaschnout pro plný dezinfekční účinek. Po aplikaci neoplachujte.</p>",
        dataSheet: "",
        properties: "<p>Bezbarvá kapalina, pH 6,0 neutrální, typický zápach alkoholu.</p>",
        safetySheet: "/downloads/amphospray safety.pdf"
    },
];

/* Template
    {
        id: ,
        category: "Dezinfekční prostředky",
        categoryColor: "#4474ac",
        link: "store.html#desinfection",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "<p></p>",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "<p></p>",
        dataSheet: "",
        properties: "<p></p>",
        safetySheet: ""
    },
*/