let combData = [   
    {
        id: 41,
        category: "Ekologická neutralizace zápachu",
        categoryColor: "#4C934C",
        link: "store.html#odor",
        productName: "ENVIRO-CHEM Cx 20 l",
        unit: "l",
        amount: 20,
        shortDescription: "Přípravek proti zapachu z organických zdrojů",
        img: "/img/enviro-chem 20.png",
        longDescription: "<p>Koncentrovaná kapalina pro přímý kontakt, neutralizující zápach, vyvinutá k zabránění uvolňování nepříjemných pachů vznikajících rozkladem organických látek. Nejedná se o maskovací prostředek ani parfém – Enviro-Chem Cx skutečně neutralizuje zápachy přímo u jejich zdroje a pomáhá předcházet vzniku nových.</p><p>Lze použít na skládkách (čelní stěny, úniky výluhů, vykládací plochy, dopravníky), kompostovací hromady, odpad v překladištích, místa exhumací na skládkách, kalová pole čistíren odpadních vod, odpadní laguny, lisy na odpad nebo jímky pro recyklaci vody z myček nákladních vozidel za účelem odstranění/eliminace zápachu.</p><p>Přípravek je také účinný při kontrole zápachu na betonových podlahách překladišť, v okolí lisů, v nádržích cisteren používaných k aplikaci prostředků pro potlačení prašnosti na komunikacích a u zametacích vozů čistících zpevněné cesty v okolí skládek a čistíren.</p><p>Zvláště užitečný v odvětvích jako jsou: myčky aut, mléčné farmy, zemědělské podniky, chovy hospodářských zvířat a výběhy, produkce mořských plodů, masokombináty, těžba, papírny, drůbeží, hygienické služby, kanalizace a čistírny odpadních vod, myčky nákladních vozidel, dřevozpracující průmysl atd.</p>",
        preicePerKg: "69900",
        pricePerKgVat: "84579",
        pricePerUnit: "1398000",
        pricePerUnitVat: "1691580",
        howToUse: "<p>Použijte zařízení s nízkým tlakem upravené pro aplikaci vlhkého postřiku. Od zahradního postřikovače až po velké postřikovací zařízení, jako je cisterna s vodou nebo pásový traktor s postřikovacími rameny připevněnými k radlici.</p><p>Lze ředit vodou až v poměru 1:1000 v závislosti na koncentraci a frekvenci aplikace.</p><p>Aplikujte roztok přímo na povrchy produkující zápach.</p>",
        dataSheet: "",
        properties: "<p>Světlá zelená kapalina, pH (koncentrát) 2,2. Zápach mírný.</p>",
        safetySheet: ""
    },
    {
        id: 42,
        category: "Ekologická neutralizace zápachu",
        categoryColor: "#4C934C",
        link: "store.html#odor",
        productName: "OLOBIO 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Tekutý neutralizátor zápachu",
        img: "/img/olobio 5.png",
        longDescription: "<p>Zabraňuje tvorbě zapáchajících složek způsobených biologickým rozkladem (např. zkažené jídlo, odpad, organická hmota).</p><p>Niči molekuly zápachu, místo aby je jen překrýval. Zanechává příjemnou vůni pro svěží prostředí.</p><p>Bezpečný pro každodenní použití v domácnostech i profesionálních prostředích. Na rozdíl od běžných osvěžovačů vzduchu, které zápach pouze maskují, Olobio jej neutralizuje na molekulární úrovni. Díky tomu je obzvlášť účinný na místech, kde se zápach neustále vrací, jako jsou odpadní prostory nebo koupelny.</p>",
        preicePerKg: "59900",
        pricePerKgVat: "72479",
        pricePerUnit: "299500",
        pricePerUnitVat: "362395",
        howToUse: "<p>Domácí odpadkové koše a popelnice: nastříkejte nebo nalijte malé množství přímo do nádoby po vyprázdnění, při přetrvávajícím zápachu aplikujte denně nebo po každém čištění.</p><p>Místnosti pro odpadky / společné odpadní prostory: nastříkejte vydatně na podlahy, stěny a kontejnery, opakujte pravidelně, abyste zabránili hromadění zápachu.</p><p>Zvířecí moč (domácí mazlíčci, útulky, kočičí toalety): aplikujte přímo na postižené místo, nechte přirozeně vyschnout.</p><p>Zapáchající dřezy a sprchy: nalijte malé množství do odpadu, nechte působit několik minut a poté opláchněte vodou.</p><p>Pouliční zametače / komunální úklid: v případě potřeby zřeďte (podle vybavení), nastříkejte na povrchy, kde se vyskytují organické pachy.</p>",
        dataSheet: "",
        properties: "<p>Čirý, mírně zeleno‑namodralý roztok. Slabý zápach po medu/mandlích, pH: 3, hustota při 20 °C: 2,6–3,2.</p>",
        safetySheet: ""
    },

];

/* Template
    {
        id: ,
        category: "Ekologická neutralizace zápachu",
        categoryColor: "#4C934C",
        link: "store.html#odor",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "",
        dataSheet: "",
        properties: "",
        safetySheet: ""
    },
*/