let specData = [   
    {
        id: 51,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Limescale Strong 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/limescale strong 5.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "104500",
        pricePerUnitVat: "126445",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:10 do vody.</p><p>Po aplikaci opláchněte vodou (teplou), aby se povrch zneutralizoval.</p><p>Může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/limescale strong data.pdf",
        properties: "<p>Modrá kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/limescale strong safety.pdf"
    },
    {
        id: 52,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Limescale Strong 25 kg",
        unit: "kg",
        amount: 25,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/limescale strong 25.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "18800",
        pricePerKgVat: "22748",
        pricePerUnit: "470000",
        pricePerUnitVat: "568700",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:10 do vody.</p><p>Po aplikaci opláchněte vodou (teplou), aby se povrch zneutralizoval.</p><p>Může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/limescale strong data.pdf",
        properties: "<p>Modrá kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/limescale strong safety.pdf"
    },
    {
        id: 53,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Red Strong 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/red strong 5.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "20900",
        pricePerKgVat: "25289",
        pricePerUnit: "104500",
        pricePerUnitVat: "126445",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:5 do vody. Po aplikaci opláchněte vodou ( i teplou), aby se povrch zneutralizoval.</p><p>Red Strong může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/red strong data.pdf",
        properties: "<p>Červená kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/red strong safety.pdf"
    },
    {
        id: 54,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "Red Strong 20 kg",
        unit: "kg",
        amount: 20,
        shortDescription: "Silně kyselý čistící přípravek na rez a vodní kámen",
        img: "/img/red strong 20.png",
        longDescription: "<p>Silně kyselý, čistící přípravek na rez a vodní kámen. Je určen pro mytí železa, plastů, kamene, cihel, zámkové dlažby, porcelánu a jako kyselé mytí betonových podlah před nanesením epoxy vrstvy nebo podlahového nátěru.</p><p>Ideální k odstranění nečistot z betonovývh podlah s natřeným povrchem, strojů a zařízení. Je velmi účinný pro čištění kamenných dlaždic, zámkové dlažby, odstraňuje vodní kámen, zbytky betonových nánosů a rez.</p>",
        preicePerKg: "18400",
        pricePerKgVat: "22264",
        pricePerUnit: "368000",
        pricePerUnitVat: "445280",
        howToUse: "<p>Používá se neředěný nebo v poměru 1:1 – 1:5 do vody. Po aplikaci opláchněte vodou ( i teplou), aby se povrch zneutralizoval.</p><p>Red Strong může odbarvit hliník, mosaz, měď a zinek.</p>",
        dataSheet: "/downloads/red strong data.pdf",
        properties: "<p>Červená kapalina, pH 1,5-2,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/red strong safety.pdf"
    },
    {
        id: 55,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "DONICLEAN IM 5 kg",
        unit: "kg",
        amount: 5,
        shortDescription: "Přípravek pro plastařský, tiskařský a metalurgický průmysl",
        img: "/img/doniclean lm 5.png",
        longDescription: "<p>Okamžité dokonalé čištění pracovních ploch vstřikovacích a lisovacích forem od zbytků plastů, separátorů a jiných nečistot. Lze použít i pro čištění zbytků některých typů barev, používaných v tiskařských strojích.</p><p>Vlastnosti výrobku: Profesionální odstraňovač zbytků plastů, olejů, tuků, vosků, separátorů a rzi z kovových ploch vstřikovacích forem pro lisování plastů či extruzi hliníkových výrobků. Čistí kovové i plastové povrchy vstřikovacích forem. Vzhledem k neutrálnímu PH lze aplikovat i na leštěné plochy forem. Odstraňuje zbytky polymerů (PVC, PA, PI, PE). Doniclean IM lze použít i na mírně zahřáté lisovací formy.</p><p>Dokonalý a rychlý účinek. Přípravek obsahuje inhibitor koroze, - zajišťuje antikorozni ochranu kovových povrchů. Produkt je speciálně vyrobený pro použití v plastařském a tiskařském průmyslu.</p><p>Příklady použití: - čištění pracovních prostorů vstřikovacích forem – rozpouštění zbytků plastů, olejů a separátorů.</p>",
        preicePerKg: "24900",
        pricePerKgVat: "30129",
        pricePerUnit: "124500",
        pricePerUnitVat: "150645",
        howToUse: "<p>Nastříkejte rozprašovačem na čištěný povrch, nechte působit a následně důkladně setřete. Při silném znečištění postup opakujte.</p>",
        dataSheet: "",
        properties: "<p>Žlutá kapalina, pH 3-8,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/doniclean lm safety.pdf"
    },
    {
        id: 56,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "DONICLEAN IM 20 kg",
        unit: "kg",
        amount: 20,
        shortDescription: "Přípravek pro plastařský, tiskařský a metalurgický průmysl",
        img: "/img/doniclean lm 20.png",
        longDescription: "<p>Okamžité dokonalé čištění pracovních ploch vstřikovacích a lisovacích forem od zbytků plastů, separátorů a jiných nečistot. Lze použít i pro čištění zbytků některých typů barev, používaných v tiskařských strojích.</p><p>Vlastnosti výrobku: Profesionální odstraňovač zbytků plastů, olejů, tuků, vosků, separátorů a rzi z kovových ploch vstřikovacích forem pro lisování plastů či extruzi hliníkových výrobků. Čistí kovové i plastové povrchy vstřikovacích forem. Vzhledem k neutrálnímu PH lze aplikovat i na leštěné plochy forem. Odstraňuje zbytky polymerů (PVC, PA, PI, PE). Doniclean IM lze použít i na mírně zahřáté lisovací formy.</p><p>Dokonalý a rychlý účinek. Přípravek obsahuje inhibitor koroze, - zajišťuje antikorozni ochranu kovových povrchů. Produkt je speciálně vyrobený pro použití v plastařském a tiskařském průmyslu.</p><p>Příklady použití: - čištění pracovních prostorů vstřikovacích forem – rozpouštění zbytků plastů, olejů a separátorů.</p>",
        preicePerKg: "19900",
        pricePerKgVat: "24079",
        pricePerUnit: "398000",
        pricePerUnitVat: "481580",
        howToUse: "<p>Nastříkejte rozprašovačem na čištěný povrch, nechte působit a následně důkladně setřete. Při silném znečištění postup opakujte.</p>",
        dataSheet: "",
        properties: "<p>Žlutá kapalina, pH 3-8,5 (3% roztok při 20 °C). Zápach: charakteristický.</p>",
        safetySheet: "/downloads/doniclean lm safety.pdf"
    },
    {
        id: 57,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "KORING-311 1 kg",
        unit: "kg",
        amount: 1,
        shortDescription: "Biologicky odbouratelný odstraňovač rzi",
        img: "/img/koring 1.png",
        longDescription: "<p>Liho-vodný roztok směsi vysoce účinných inhibitorů koroze a pasivačních složek. Chrání svým antikorozním účinkem všechny kovy. Při ponorovém použití odstraňuje korozi a některé minerální usazeniny.</p><p>Napadá barvy a při delším působení je schopen je zcela odstranit. Je možné na jím ošetřený povrch provádět, přímo bez odstraňování, jakoukoliv povrchovou úpravu, nanést jakoukoliv barvu. Barva dokonce získá antikorozní vlastnosti.</p><p>Není vhodné jej používat tam, kam má přístup voda, která by jej odplavila, a i když pasivace by jako ochrana fungovala dál, většina protikorozního účinku by byla ztracena.</p><p>Prostředek je biologicky odbouratelný podle předpisů EU.</p>",
        preicePerKg: "59900",
        pricePerKgVat: "72479",
        pricePerUnit: "59900",
        pricePerUnitVat: "72479",
        howToUse: "<p>Je možné ředit vodou a je ve vodě rozpustný. Antikorozně působí 30 cm ve vzdálenosti od místa, kam byl nanesen, a to díky svým parám. Rychle schne.</p><p>Příklady nejčastějších způsobů použití:</p><p>1. Prostředek byl vyvinut pro použití v průmyslových pračkách, jako poslední konzervační stupeň praní. Takto ošetřený výrobek je dlouhodobě nakonzervován a chráněn proti korozi. Do praček se prostředek ředí.</p><p>2. Výrobek je používán restaurátory historických automobilů. Jakmile jsou nějaký díl nebo karoserie opískovány, ihned se štětcem nanese prostředek. Ten pak dlouhodobě chrání opískovaný výrobek. Nebo jím vystříkají všechny dutiny automobilu přičemž páry prostředku se dostanou i do nepřístupných míst. Pro tyto aplikace se používá koncentrát.</p><p>3. Při výrobě velkých ocelových zásobníků o objemu desítek m3, se jím natírá vnitřní i vnější povrch, aby byl zásobník protikorozně chráněn než je uveden do provozu. Aplikace koncentrátu.</p><p>4. U výrobků, kde se provádí tlaková zkouška, se používá tento prostředek jako tlakové médium v naředěné formě.</p><p>5. V procesech, kde se používá pískování a opískované výrobky mají být delší dobu skladovány, se používá nános koncentrátu nebo i ředěný prostředek na jejich konzervaci.</p><p>6. Při ochraně starší techniky, která má korozní „výkvěty“ viditelné přes barvu, se na celou plochu nanese koncentrát prostředku. Ten projde barvou až na kov, korozi zastaví a pokud je barva narušená moc, tak ji odstraní. Například historické vojenské vagóny v muzeu v Milovicích, zevnitř i zvenčí kompletně ošetřili tímto prostředkem.</p><p>7. V muzejní praxi se prostředek ve formě koncentrátu používá ponorově, pokud je zapotřebí ze sbírkového předmětu odstranit barvu, rez nebo měděnku a současně kovový předmět nakonzervovat.</p><p>8. Vzhledem k tomu, že prostředek blokuje reakce kyslíku, používá se také na hubení nežádoucích rostlin a trávy. Nejedná se o herbicid, protože rostlina je tímto prostředkem udušena. Výhodou je, že prostředek je v půdě rychle biologicky odbouratelný. Je však nutné jej používat opakovaně, protože na semena nemá účinek.</p><img style='width: 5rem' src='img/alert.png'><p>Při práci s prostředkem používat ochranné rukavice a zejména chránit oči brýlemi nebo štítem. Při potřísnění pokožky opláchnou dostatečným množstvím vody a ošetřit regeneračním krémem. Vážné komplikace mohou nastat, pokud se prostředek dostane do očí. Ty ypláchnout velkým množstvím vody a navštívit lékaře. Prostředek se nedoporučuje nanášet stříkáním, vzniklý aerosol se vzduchem by mohl poškodit oči a plíce.</p>",
        dataSheet: "/downloads/koring data.pdf",
        properties: "<p>Roztok má nahnědlou barvu a charakteristický zápach.</p>",
        safetySheet: "/downloads/koring safety.pdf"
    },
    {
        id: 58,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "KORING-311 25 kg",
        unit: "kg",
        amount: 25,
        shortDescription: "Biologicky odbouratelný odstraňovač rzi",
        img: "/img/koring 25.png",
        longDescription: "<p>Liho-vodný roztok směsi vysoce účinných inhibitorů koroze a pasivačních složek. Chrání svým antikorozním účinkem všechny kovy. Při ponorovém použití odstraňuje korozi a některé minerální usazeniny.</p><p>Napadá barvy a při delším působení je schopen je zcela odstranit. Je možné na jím ošetřený povrch provádět, přímo bez odstraňování, jakoukoliv povrchovou úpravu, nanést jakoukoliv barvu. Barva dokonce získá antikorozní vlastnosti.</p><p>Není vhodné jej používat tam, kam má přístup voda, která by jej odplavila, a i když pasivace by jako ochrana fungovala dál, většina protikorozního účinku by byla ztracena.</p><p>Prostředek je biologicky odbouratelný podle předpisů EU.</p>",
        preicePerKg: "49700",
        pricePerKgVat: "60137",
        pricePerUnit: "1242500",
        pricePerUnitVat: "1503425",
        howToUse: "<p>Je možné ředit vodou a je ve vodě rozpustný. Antikorozně působí 30 cm ve vzdálenosti od místa, kam byl nanesen, a to díky svým parám. Rychle schne.</p><p>Příklady nejčastějších způsobů použití:</p><p>1. Prostředek byl vyvinut pro použití v průmyslových pračkách, jako poslední konzervační stupeň praní. Takto ošetřený výrobek je dlouhodobě nakonzervován a chráněn proti korozi. Do praček se prostředek ředí.</p><p>2. Výrobek je používán restaurátory historických automobilů. Jakmile jsou nějaký díl nebo karoserie opískovány, ihned se štětcem nanese prostředek. Ten pak dlouhodobě chrání opískovaný výrobek. Nebo jím vystříkají všechny dutiny automobilu přičemž páry prostředku se dostanou i do nepřístupných míst. Pro tyto aplikace se používá koncentrát.</p><p>3. Při výrobě velkých ocelových zásobníků o objemu desítek m3, se jím natírá vnitřní i vnější povrch, aby byl zásobník protikorozně chráněn než je uveden do provozu. Aplikace koncentrátu.</p><p>4. U výrobků, kde se provádí tlaková zkouška, se používá tento prostředek jako tlakové médium v naředěné formě.</p><p>5. V procesech, kde se používá pískování a opískované výrobky mají být delší dobu skladovány, se používá nános koncentrátu nebo i ředěný prostředek na jejich konzervaci.</p><p>6. Při ochraně starší techniky, která má korozní „výkvěty“ viditelné přes barvu, se na celou plochu nanese koncentrát prostředku. Ten projde barvou až na kov, korozi zastaví a pokud je barva narušená moc, tak ji odstraní. Například historické vojenské vagóny v muzeu v Milovicích, zevnitř i zvenčí kompletně ošetřili tímto prostředkem.</p><p>7. V muzejní praxi se prostředek ve formě koncentrátu používá ponorově, pokud je zapotřebí ze sbírkového předmětu odstranit barvu, rez nebo měděnku a současně kovový předmět nakonzervovat.</p><p>8. Vzhledem k tomu, že prostředek blokuje reakce kyslíku, používá se také na hubení nežádoucích rostlin a trávy. Nejedná se o herbicid, protože rostlina je tímto prostředkem udušena. Výhodou je, že prostředek je v půdě rychle biologicky odbouratelný. Je však nutné jej používat opakovaně, protože na semena nemá účinek.</p><img style='width: 5rem' src='img/alert.png'><p>Při práci s prostředkem používat ochranné rukavice a zejména chránit oči brýlemi nebo štítem. Při potřísnění pokožky opláchnou dostatečným množstvím vody a ošetřit regeneračním krémem. Vážné komplikace mohou nastat, pokud se prostředek dostane do očí. Ty ypláchnout velkým množstvím vody a navštívit lékaře. Prostředek se nedoporučuje nanášet stříkáním, vzniklý aerosol se vzduchem by mohl poškodit oči a plíce.</p>",
        dataSheet: "/downloads/koring data.pdf",
        properties: "<p>Roztok má nahnědlou barvu a charakteristický zápach.</p>",
        safetySheet: "/downloads/koring safety.pdf"
    },
];

/* Template
    {
        id: ,
        category: "Speciální prostředky",
        categoryColor: "#c13540",
        link: "store.html#special",
        productName: "",
        unit: "",
        amount: ,
        shortDescription: "",
        img: "/img/canister.jpg",
        longDescription: "<p></p>",
        preicePerKg: "",
        pricePerKgVat: "",
        pricePerUnit: "",
        pricePerUnitVat: "",
        howToUse: "<p></p>",
        dataSheet: "",
        properties: "<p></p>",
        safetySheet: ""
    },
*/